backend:
  name: git-gateway
  branch: main  # 或者 master，根据你的仓库默认分支

media_folder: "source/images/uploads"    # 上传文件保存位置
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "source/_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: [] }
      - { label: "Categories", name: "categories", widget: "list", default: [] }
      - { label: "Body", name: "body", widget: "markdown" }
